### ISSUE TITLE
Error when trying to close a position

### ISSUE THREAD

**Issue by johndkn** [fxcm/fxcmrest-php#5]
Hello,

When I try to close a position, I receive the error below.

Please note I've already implemented the change mentioned in #3.

Thanks in advance,
Jonathan

```
Error: Uncaught Error: Class 'FxcmRest\Exception' not found in /var/www/suntrading/prod/vendor/fxcm/fxcmrest/src/SocketIO.php:169
Stack trace:
#0 /var/www/suntrading/prod/vendor/fxcm/fxcmrest/src/SocketIO.php(178): FxcmRest\SocketIO->wsdata('ter>cloudflare<...')
#1 /var/www/suntrading/prod/vendor/fxcm/fxcmrest/src/SocketIO.php(178): FxcmRest\SocketIO->wsdata(' Request</title...')
#2 /var/www/suntrading/prod/vendor/fxcm/fxcmrest/src/SocketIO.php(178): FxcmRest\SocketIO->wsdata('tent-Type: text...')
#3 /var/www/suntrading/prod/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): FxcmRest\SocketIO->wsdata('HTTP/1.1 400 Ba...')
#4 /var/www/suntrading/prod/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit('data', Array)
#5 /var/www/suntrading/prod/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Stream\Util::React\Stream\{closure}('HTTP/1.1 400 Ba...')
#6 /var/www/suntrading/prod/vendor/react/stream/src/DuplexResourceStream.php(193): Evenement\EventEmitter->emit(
169: /var/www/suntrading/prod/vendor/fxcm/fxcmrest/src/SocketIO.php
BACKTRACE:

	Line unknown: unknown
		More:
			Function:shutdown			Class:PhpErrorHandler			Object:{}
```

**Comment by PlanetTheCloud** [comment]
Fixed with PR #7
